version: '3'
services:
  tradetree_mysql:
    image: mysql:5.7
    container_name: tradetree_mysql
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./db_dumps:/home/db_dumps"
    restart: unless-stopped
    command: --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tradetree
      - MYSQL_USER=tradetree
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'
    networks:
      - tradetree
    platform: linux/x86_64
  phpmyadmin:
    container_name: tradetree_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - tradetree_mysql
    restart: unless-stopped
    ports:
      - '8011:80'
    environment:
      PMA_HOST: tradetree_mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - tradetree
    platform: linux/x86_64

  laravel-env:
    build: ./dockerfiles
    container_name: tradetree_laravel
    restart: unless-stopped
    depends_on:
      - tradetree_mysql
    volumes:
      - "../tradetree-laravel:/var/www/laravel"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    networks:
      - tradetree
    platform: linux/x86_64
  nginx:
    image: nginx:alpine
    container_name: tradetree_nginx
    depends_on:
      - laravel-env
    volumes:
      - "../tradetree-laravel:/var/www/laravel"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./dockerfiles/config/nginx/certs/:/etc/nginx/certs/"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - tradetree
    platform: linux/x86_64

  redis:
    container_name: tradetree_redis
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redislocalpassword
    volumes:
      - cache:/data
    networks:
      - tradetree

  crdb-0:
    container_name: crdb-0
    hostname: crdb-0
    platform: linux/x86_64
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=ttobma-crdb --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    networks:
      - tradetree

  crdb-1:
    container_name: crdb-1
    hostname: crdb-1
    platform: linux/x86_64
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=ttobma-crdb --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    depends_on:
      - crdb-0
    networks:
      - tradetree

  crdb-2:
    container_name: crdb-2
    hostname: crdb-2
    platform: linux/x86_64
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=ttobma-crdb --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    depends_on:
      - crdb-0
    networks:
      - tradetree

  lb:
    container_name: lb
    hostname: lb
    build: ./docker/nginx_lb
    ports:
      - "26257:26257"
      - "20150:20150"
      - "8080:8080"
    depends_on:
      - crdb-0
      - crdb-1
      - crdb-2
    volumes:
      - "./db_dumps:/mnt/cockroach-exports"
    networks:
      - tradetree

  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    platform: linux/x86_64
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb-0:26257
      - COCKROACH_INSECURE=true
      - COCKROACH_INIT=true
      - DATABASE_NAME=tradetree
    depends_on:
      - lb
    networks:
      - tradetree

networks:
  tradetree:
    driver: bridge

volumes:
  cache:
    driver: local