#include:
#    - ./docker/cdb/cdb.yml

services:
#    redis:
#        container_name: ttobma-redis
#        restart: unless-stopped
#        build:
#            context: .
#            dockerfile: docker/redis.docker
#        command: redis-server --save 20 1
#        ports:
#            - 6379:${REDIS_PORT}
#        networks:
#            - ttobma
    php:
        container_name: ttonew-php
        restart: unless-stopped
        working_dir: ${APP_ROOT}
        build:
            context: ./
            dockerfile: docker/php.docker
        volumes:
            - ./:${APP_ROOT}
        networks:
            - ttobma
            - ttobma-old_ttobma

#    nginx:
#        container_name: ttobma-nginx
#        restart: unless-stopped
#        build:
#            context: .
#            dockerfile: docker/nginx.docker
#        ports:
#            - 443:${APP_PORT}
#        environment:
#            - APP_DOMAIN=${APP_DOMAIN}
#            - APP_ROOT=${APP_ROOT}
#            - APP_PORT=${APP_PORT}
#        volumes:
#            - ./:${APP_ROOT}
#        networks:
#            ttobma:
#                aliases:
#                    - ${APP_URL}
#        depends_on:
#            - php
#            - cdb-na
#            - cdb-eu
#            - cdb-cn

networks:
    ttobma:
        driver: bridge
    ttobma-old_ttobma:
        external: true

#volumes:
#    cache:
#        driver: local
