services:
    php:
        container_name: ttonew-php
        restart: unless-stopped
        working_dir: ${APP_ROOT}
        build:
            context: ./
            dockerfile: docker/php.docker
        ports:
            - 5173:5173
        volumes:
            - /var/www/html:/var/www/html
            - ${APP_ROOT}:${APP_ROOT}
        networks:
            - ttobma-new
            - ttobma-old

networks:
    ttobma-new:
        driver: bridge
        name: ttobma-new
    ttobma-old:
        external: true
