services:
    php:
        container_name: ttonew-php
        restart: unless-stopped
        working_dir: ${APP_ROOT}
        build:
            context: ./
            dockerfile: docker/php.docker
        volumes:
            - ./:${APP_ROOT}
        networks:
            - ttobma-new
            - ttobma-old

    nginx:
        container_name: ttonew-nginx
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/nginx.docker
#        links:
#            - ttobma-nginx
#        ports:
#            - ${APP_PORT}:${APP_PORT}
        environment:
            - APP_DOMAIN=${APP_DOMAIN}
            - APP_ROOT=${APP_ROOT}
            - APP_PORT=${APP_PORT}
        volumes:
            - ${APP_ROOT}:${APP_ROOT}
        networks:
            ttobma-old:
                aliases:
                    - ${APP_URL}
        depends_on:
            - php

networks:
    ttobma-new:
        driver: bridge
    ttobma-old:
        external: true
        name: ttobma-old_ttobma-old
