services:
  cdb-cert:
    container_name: cdb-cert
    hostname: cdb-cert
    build:
      context: .
      dockerfile: certs.docker
    volumes:
      - certs-na:/certs/cdb-na
      - certs-eu:/certs/cdb-eu
      - certs-cn:/certs/cdb-cn
      - certs-client:/certs/client

  cdb-na:
    container_name: cdb-na
    hostname: cdb-na
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=cdb-secure --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=cdb-na --locality=region=NA,zone=NA-1
    volumes:
      - certs-na:/certs
    depends_on:
      - cdb-cert
    networks:
      - ttobma

  cdb-eu:
    container_name: cdb-eu
    hostname: cdb-eu
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=cdb-secure --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=cdb-na --locality=region=EU,zone=EU-1
    volumes:
      - certs-eu:/certs
    depends_on:
      - cdb-cert
      - cdb-na
    networks:
      - ttobma

  cdb-cn:
    container_name: cdb-cn
    hostname: cdb-cn
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=cdb-secure --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=cdb-na --locality=region=CN,zone=CN-1
    volumes:
      - certs-cn:/certs
    depends_on:
      - cdb-cert
      - cdb-na
    networks:
      - ttobma

  cdb-init:
    container_name: cdb-init
    hostname: cdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=cdb-na:26257
      - COCKROACH_INSECURE=false
      - COCKROACH_CERTS_DIR=/certs
      - COCKROACH_INIT=true
      - DATABASE_NAME=cdb_default
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - COCKROACH_ORG=${DB_ORG}
      - COCKROACH_LICENSE_KEY=${DB_KEY}
    volumes:
      - certs-client:/certs
    depends_on:
      - nginx
      - cdb-cert
    networks:
      - ttobma

volumes:
  certs-na:
  certs-eu:
  certs-cn:
  certs-client: